# Generated by Django 3.1 on 2021-07-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_name', models.CharField(max_length=255, verbose_name='权限名称')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='权限路径')),
                ('level', models.IntegerField(default=1, verbose_name='权限级别')),
                ('children', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='menu.permission')),
            ],
            options={
                'verbose_name': '权限基础信息列表',
                'verbose_name_plural': '权限基础信息列表',
                'db_table': 'permission',
            },
        ),
    ]
