# Generated by Django 3.0.5 on 2020-07-23 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('category_type', models.SmallIntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], verbose_name='商品分类级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 7, 23, 21, 44, 11, 607712), help_text='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父级类目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('goods_sn', models.CharField(max_length=50, verbose_name='商品唯一编号')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('sold_num', models.IntegerField(default=0, verbose_name='商品销售量')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('goods_num', models.IntegerField(default=0, verbose_name='库存数')),
                ('market_price', models.DecimalField(decimal_places=3, default=0, max_digits=11, verbose_name='市场价格')),
                ('shop_price', models.DecimalField(decimal_places=3, default=0, max_digits=11, verbose_name='本店价格')),
                ('descripte', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品描述')),
                ('goods_front_image', models.CharField(blank=True, max_length=40, null=True, verbose_name='封面图')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热销', verbose_name='是否热销')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
