# Generated by Django 3.1 on 2021-07-20 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 16, 34, 44, 615751), help_text='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父级类目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.goodscategory'),
        ),
    ]
