# Generated by Django 3.1 on 2021-07-20 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210720_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 16, 44, 30, 525685), help_text='添加时间'),
        ),
    ]
