# Generated by Django 3.1 on 2021-07-20 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210720_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 16, 46, 4, 357902), help_text='添加时间'),
        ),
    ]
